#authenticate once by chaning the player via the official app

zeroconf_enabled: true # Whether to keep the device discoverable at all times, even if authenticated via other means
zeroconf_port: 0       # The port to use for Zeroconf, 0 for random
zeroconf_backend: builtin
credentials:
  type: zeroconf
  zeroconf:
    persist_credentials: true # Whether to persist zeroconf user credentials even after disconnecting; Will work withoput the client

bitrate: 160
name: "SpotAmp Player"

server:
  enabled: true
  address: "127.0.0.1"
  port: 3678
